apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-nginx
  template:
    metadata:
      labels:
        app: flask-nginx
    spec:
      containers:
        - name: flask
          image: gcr.io/ece-9016-group-02-project/todo-backend
          ports:
            - containerPort: 5000
        - name: nginx  # This starts a new container definition at the correct level
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-html-volume
              mountPath: /usr/share/nginx/html
      volumes:  # 'volumes' should be aligned with 'containers'
        - name: nginx-config-volume
          configMap:
            name: nginx-config
        - name: nginx-html-volume
          configMap:
            name: nginx-html-config
      affinity:  # 'affinity' should also be aligned with 'containers' and 'volumes'
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - flask-nginx
                      - mysql
              topologyKey: "kubernetes.io/hostname"
